export * from './getCoordinates'
export * from '../components/BattleField/getArrId'
export * from './initFlot'
export * from './initField'
export * from './isTryPlace'
export * from './isCoordinateIn'
